<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
   //
    protected $table = "products";
    protected $fillable = [
        'name' , 
        'cat_id' , 
        'hashtag' , 
        'descr' , 
        'custom_field' , 
        'price' ,
        'quantity' , 
        'dealer_id',
        'slug',
        'image_url'
    ];

    /**
     * Display the specified resource.
     *
     * @param  int  
     * @return Response
     */
    public function dealer ()
    {
    	
    	return $this->belongsTo(Dealer::class);
    
    }

    /**
     * Display the specified resource.
     *
     * @param  int  
     * @return Response
     */
    public function category()
    {
        
    	return $this->belongsTo(Category::class,'cat_id');
    
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($product) {

            $product->slug = str_slug($product->name);

            if (static::whereSlug($product->slug)->exists()) {
               $product->slug .= '-' . uniqid();
            }

        });
    }

}
