<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
   //
    protected $table = "products";

    protected $fillable = ['id','name','descr','price','quantity','image_url','hashtag','custom_field','slug','cat_id','dealer_id','image_url','created_at','updated_at'];

    /**
     * Display the specified resource.
     *
     * @param  int  
     * @return Response
     */
    public function dealer ()
    {
    	
    	return $this->belongsTo(Dealer::class);
    
    }

    /**
     * Display the specified resource.
     *
     * @param  int  
     * @return Response
     */
    public function category()
    {
        
    	return $this->belongsTo(Category::class,'cat_id');
    
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($product) {

            $product->slug = str_slug($product->name);

            if (static::whereSlug($product->slug)->exists()) {
               $product->slug .= '-' . uniqid();
            }

        });
    }

}
